CREATE TABLE POST (
    ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
    title VARCHAR(400) NOT NULL,
    content VARCHAR(400) NULL,
    created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COMMENT (
    id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    post_id BIGINT NOT NULL,
    content VARCHAR(400) NULL,
    created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
 );

 ALTER TABLE COMMENT
    ADD CONSTRAINT comment_post_id
    FOREIGN KEY (post_id) REFERENCES POST(id);


